export const TOOL_TIP_MESSAGES = {
    shareResume: 'Share your resume with other members of the Pro-Filer community.',
    ifCurrentlyEmployed: "If you are currently employed, set the end date of your last job to today's date. It will show as 'present' in your resume."
};

export const STATES_DROPDOWN = [
    { name: 'Alabama', abbreviation: 'AL' },
    { name: 'Alaska', abbreviation: 'AK' },
    { name: 'Arizona', abbreviation: 'AZ' },
    { name: 'Arkansas', abbreviation: 'AR' },
    { name: 'California', abbreviation: 'CA' },
    { name: 'Colorado', abbreviation: 'CO' },
    { name: 'Connecticut', abbreviation: 'CT' },
    { name: 'Delaware', abbreviation: 'DE' },
    { name: 'Florida', abbreviation: 'FL' },
    { name: 'Georgia', abbreviation: 'GA' },
    { name: 'Hawaii', abbreviation: 'HI' },
    { name: 'Idaho', abbreviation: 'ID' },
    { name: 'Illinois', abbreviation: 'IL' },
    { name: 'Indiana', abbreviation: 'IN' },
    { name: 'Iowa', abbreviation: 'IA' },
    { name: 'Kansas', abbreviation: 'KS' },
    { name: 'Kentucky', abbreviation: 'KY' },
    { name: 'Louisiana', abbreviation: 'LA' },
    { name: 'Maine', abbreviation: 'ME' },
    { name: 'Maryland', abbreviation: 'MD' },
    { name: 'Massachusetts', abbreviation: 'MA' },
    { name: 'Michigan', abbreviation: 'MI' },
    { name: 'Minnesota', abbreviation: 'MN' },
    { name: 'Mississippi', abbreviation: 'MS' },
    { name: 'Missouri', abbreviation: 'MO' },
    { name: 'Montana', abbreviation: 'MT' },
    { name: 'Nebraska', abbreviation: 'NE' },
    { name: 'Nevada', abbreviation: 'NV' },
    { name: 'New Hampshire', abbreviation: 'NH' },
    { name: 'New Jersey', abbreviation: 'NJ' },
    { name: 'New Mexico', abbreviation: 'NM' },
    { name: 'New York', abbreviation: 'NY' },
    { name: 'North Carolina', abbreviation: 'NC' },
    { name: 'North Dakota', abbreviation: 'ND' },
    { name: "Ohio", abbreviation: "OH" },
    { name: 'Oklahoma', abbreviation: 'OK' },
    { name: 'Oregon', abbreviation: 'OR' },
    { name: 'Pennsylvania', abbreviation: 'PA' },
    { name: 'Rhode Island', abbreviation: 'RI' },
    { name: 'South Carolina', abbreviation: 'SC' },
    { name: 'South Dakota', abbreviation: 'SD' },
    { name: 'Tennessee', abbreviation: 'TN' },
    { name: 'Texas', abbreviation: 'TX' },
    { name: 'Utah', abbreviation: 'UT' },
    { name: 'Vermont', abbreviation: 'VT' },
    { name: 'Virginia', abbreviation: 'VA' },
    { name: 'Washington', abbreviation: 'WA' },
    { name: 'West Virginia', abbreviation: 'WV' },
    { name: 'Wisconsin', abbreviation: 'WI' },
    { name: 'Wyoming', abbreviation: 'WY' },
    { name: 'District of Columbia', abbreviation: 'DC' },
    { name: 'American Samoa', abbreviation: 'AS' },
    { name: 'Guam', abbreviation: 'GU' },
    { name: 'Northern Mariana Islands', abbreviation: 'MP' },
    { name: 'Puerto Rico', abbreviation: 'PR' },
    { name: 'U.S. Virgin Islands', abbreviation: 'VI' },
    { name: 'Other', abbreviation: 'OT' }
];

export const DEGREE_OPTIONS = [
    { name: 'High School Diploma', value: 'highSchool' },
    { name: 'Associate Degree', value: 'associate' },
    { name: 'Bachelor\'s Degree', value: 'bachelor' },
    { name: 'Master\'s Degree', value: 'master' },
    { name: 'Doctorate', value: 'doctorate' },
    { name: 'Professional Degree', value: 'professional' },
    { name: 'Certificate', value: 'certificate' },
    { name: 'Medical Degree', value: 'medical' },
    { name: 'PhD', value: 'phd' },
    { name: 'Law Degree', value: 'law' },
    { name: 'Trade School', value: 'trade' },
    { name: 'Vocational Training', value: 'vocational' },
    { name: 'Other', value: 'other' },
    { name: 'No Degree', value: 'noDegree' }
];