export const TOOL_TIP_MESSAGES = {
    shareResume: 'Share your resume with other members of the Pro-Filer community.',
    ifCurrentlyEmployed: "If you are currently employed, set the end date of your last job to today's date. It will show as 'present' in your resume.",
    stateWillBeAbbreviated: 'The state that you select will be entered as an abbreviation in your resume',
    editExperienceMessage: 'Edit your experience details here. You can update your job title, employer, and other relevant information.',
    editEducationMessage: 'Edit your education details here. You can update your degree, institution, and other relevant information.',
};

export const STATES_DROPDOWN = [
    { name: 'Alabama', value: 'AL' },
    { name: 'Alaska', value: 'AK' },
    { name: 'Arizona', value: 'AZ' },
    { name: 'Arkansas', value: 'AR' },
    { name: 'California', value: 'CA' },
    { name: 'Colorado', value: 'CO' },
    { name: 'Connecticut', value: 'CT' },
    { name: 'Delaware', value: 'DE' },
    { name: 'Florida', value: 'FL' },
    { name: 'Georgia', value: 'GA' },
    { name: 'Hawaii', value: 'HI' },
    { name: 'Idaho', value: 'ID' },
    { name: 'Illinois', value: 'IL' },
    { name: 'Indiana', value: 'IN' },
    { name: 'Iowa', value: 'IA' },
    { name: 'Kansas', value: 'KS' },
    { name: 'Kentucky', value: 'KY' },
    { name: 'Louisiana', value: 'LA' },
    { name: 'Maine', value: 'ME' },
    { name: 'Maryland', value: 'MD' },
    { name: 'Massachusetts', value: 'MA' },
    { name: 'Michigan', value: 'MI' },
    { name: 'Minnesota', value: 'MN' },
    { name: 'Mississippi', value: 'MS' },
    { name: 'Missouri', value: 'MO' },
    { name: 'Montana', value: 'MT' },
    { name: 'Nebraska', value: 'NE' },
    { name: 'Nevada', value: 'NV' },
    { name: 'New Hampshire', value: 'NH' },
    { name: 'New Jersey', value: 'NJ' },
    { name: 'New Mexico', value: 'NM' },
    { name: 'New York', value: 'NY' },
    { name: 'North Carolina', value: 'NC' },
    { name: 'North Dakota', value: 'ND' },
    { name: "Ohio", value: "OH" },
    { name: 'Oklahoma', value: 'OK' },
    { name: 'Oregon', value: 'OR' },
    { name: 'Pennsylvania', value: 'PA' },
    { name: 'Rhode Island', value: 'RI' },
    { name: 'South Carolina', value: 'SC' },
    { name: 'South Dakota', value: 'SD' },
    { name: 'Tennessee', value: 'TN' },
    { name: 'Texas', value: 'TX' },
    { name: 'Utah', value: 'UT' },
    { name: 'Vermont', value: 'VT' },
    { name: 'Virginia', value: 'VA' },
    { name: 'Washington', value: 'WA' },
    { name: 'West Virginia', value: 'WV' },
    { name: 'Wisconsin', value: 'WI' },
    { name: 'Wyoming', value: 'WY' },
    { name: 'District of Columbia', value: 'DC' },
    { name: 'American Samoa', value: 'AS' },
    { name: 'Guam', value: 'GU' },
    { name: 'Northern Mariana Islands', value: 'MP' },
    { name: 'Puerto Rico', value: 'PR' },
    { name: 'U.S. Virgin Islands', value: 'VI' },
    { name: 'Other', value: 'OT' }
];

export const DEGREE_OPTIONS = [
    { name: 'High School Diploma', value: 'highSchool' },
    { name: 'Associate Degree', value: 'associate' },
    { name: 'Bachelor\'s Degree', value: 'bachelor' },
    { name: 'Master\'s Degree', value: 'master' },
    { name: 'Doctorate', value: 'doctorate' },
    { name: 'Professional Degree', value: 'professional' },
    { name: 'Certificate', value: 'certificate' },
    { name: 'Medical Degree', value: 'medical' },
    { name: 'PhD', value: 'phd' },
    { name: 'Law Degree', value: 'law' },
    { name: 'Trade School', value: 'trade' },
    { name: 'Vocational Training', value: 'vocational' },
    { name: 'Other', value: 'other' },
    { name: 'No Degree', value: 'noDegree' }
];

export const TEMPLATES = [
    { name: 'Default', value: 'default' },
    { name: 'Chronological', value: 'chronological' },
    { name: 'Functional', value: 'functional' },
    { name: 'Combination', value: 'combination' },
    { name: 'Modern', value: 'modern' },
    { name: 'Simple', value: 'simple' },
    { name: 'Creative', value: 'creative' },
];


export const URL = {
    serverPort: "http://localhost:8080/",
    Auth: "api/v1/profiler/auth",
    Resume: "api/v1/profiler/resumes",
    User: "api/v1/profiler/users",
    Experience: "api/v1/profiler/experiences",
    Education: "api/v1/profiler/educations",
}